universe = vanilla
Executable = sub_GoF.sh
output                = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/Models_Tprime675/GoF/jobs/sub_GoF.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/Models_Tprime675/GoF/jobs/sub_GoF.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/Models_Tprime675/GoF/jobs/sub_GoF.$(ClusterId).log

on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

+JobFlavour = "workday"
Queue

