executable          = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_AsymptoticLimits_Tprime700.sh
output              = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_AsymptoticLimits_Tprime700.sh.out
error               = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_AsymptoticLimits_Tprime700.sh.err
log                 = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/t2w_jobs/t2w_AsymptoticLimits_Tprime700.sh.log
+JobFlavour         = "workday"
RequestCpus         = 4
queue
