universe = vanilla
Executable = sub_toys_9.sh
Arguments = 9
output                = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/Models_Tprime700/toys/jobs/sub_toys_9.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/Models_Tprime700/toys/jobs/sub_toys_9.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/p/prsaha/public/FinalFit_lite/CMSSW_10_2_13/src/flashggFinalFit/Combine/Models_Tprime700/toys/jobs/sub_toys_9.$(ClusterId).log

on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)

+JobFlavour = "espresso"
Queue

